# Generated by Django 4.2.8 on 2025-05-16 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content_preview", models.TextField(blank=True)),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                (
                    "chat_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("txt", "Text Document"),
                            ("docx", "Word Document"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionDocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("embedding_vector", models.BinaryField(blank=True, null=True)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.sessiondocument",
                    ),
                ),
            ],
            options={
                "ordering": ["session_document", "chunk_index"],
                "unique_together": {("session_document", "chunk_index")},
            },
        ),
        migrations.AddIndex(
            model_name="sessiondocument",
            index=models.Index(
                fields=["session_id"], name="knowledge_s_session_d8705d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessiondocument",
            index=models.Index(
                fields=["chat_id"], name="knowledge_s_chat_id_99aa05_idx"
            ),
        ),
    ]
