# Generated by Django 4.2.8 on 2025-05-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_sessiondocument_sessiondocumentchunk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiondocument",
            name="document_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
